// <auto-generated />
namespace ClinicProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addclinicIdtoStaffType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addclinicIdtoStaffType));
        
        string IMigrationMetadata.Id
        {
            get { return "202101052252090_add-clinicId-to-StaffType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
