// <auto-generated />
namespace ClinicProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TurnBugsFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TurnBugsFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "202101022217548_Turn-Bugs-Fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
